[package]
name = "timestamp-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { versions = "3.1.18", features = ["cargo"] }
chrono = "0.4.19"
